export const colors = {
  first: "#1a2f3a",
  primary: "#f5f5f5",
  second: "#adadad",
  // third: "#77ccf9",
  third: "#cacaca",
  brandSecond: "#6BC3AA",
  brandThird: "#F1B44F",
  supportFirst: "#6C7F7A",
  supportSecond: "#DEDAC7",
  grayUnactive: "#979797",
  grayActive: "#606060",
  grayDisabled: "#E0E0E0",
  orangeLight: "#e8bb97",
  white: "#FFF",
};
